### PR TITLE
chore(main): release web 1.0.0

### PR DESCRIPTION
**Pull request by ChecksumDev**
:robot: I have created a release *beep* *boop*
---

### Features

* added and cleaned code of mod page, fixed auth problems ([197c2c0](https://github.com/beat-forge/clients/commit/197c2c06d0cd887d92be7dfce567204ab54fa16c))
* added auth to navbar ([9feeccc](https://github.com/beat-forge/clients/commit/9feeccc3eec8a2a484a9d69500355efc9477230c))
* added dropdown in navbar for small screens, changed customClasses name for icons ([346ee2a](https://github.com/beat-forge/clients/commit/346ee2a0fb7a4075654bba7d580721d68e38527e))
* added functional pagination ([e916b26](https://github.com/beat-forge/clients/commit/e916b26598ca1ac2bdaa8594da0a9fd3e4c80f6a))
* callback github page ([78cb01d](https://github.com/beat-forge/clients/commit/78cb01d39b053c8c675a1ce6e0e02096f7caea59))
* error page ([0063c30](https://github.com/beat-forge/clients/commit/0063c304a6a905b4462242c2374ba9f85488bd5f))
* gui ([d1ecd13](https://github.com/beat-forge/clients/commit/d1ecd138684697ddf3031b433751732d3ca192b0))
* made sort working ([24ba9e3](https://github.com/beat-forge/clients/commit/24ba9e37ae66501702349634ee6d9f7a25fef143))
* profile page ([bfd21d6](https://github.com/beat-forge/clients/commit/bfd21d6413d969f5919de45e5afbd4e899fc2f2d))
* search, versions, and mod items ([e6240bb](https://github.com/beat-forge/clients/commit/e6240bb1b529ed6e3fa72f9b33d09be9116d71b6))
* **ui:** implement focus styles for link+btn ([4bde5ba](https://github.com/beat-forge/clients/commit/4bde5ba62040f585962129ed24c17db28e728204))
* **web:** add analytics ([84c5f9a](https://github.com/beat-forge/clients/commit/84c5f9a0095fe812cd7d951bb1367d6f4e4a7d14))
* **web:** beginning of landing page v2 ([437e8c5](https://github.com/beat-forge/clients/commit/437e8c561f4eb5465f2a50ac18b024bbb6e493f1))
* **web:** discord CTAs on discover and client ([6ed92c9](https://github.com/beat-forge/clients/commit/6ed92c9408ea94b50d209f5cacec99f590a9c2d0))
* **web:** functional instant mod search on discovery ([e9fc412](https://github.com/beat-forge/clients/commit/e9fc4121f41d82d7562c1483cf203d514c72b59e))
* **web:** implement ui/link ([51abe60](https://github.com/beat-forge/clients/commit/51abe6030b7b392a903ca85dad1155fbed3cebc1))
* **web:** implement ui/link in navbar ([8c5d244](https://github.com/beat-forge/clients/commit/8c5d2445265415fd2e60b8bdc122bce481479f10))
* **web:** init analytics events on nav/footer/ctas ([e7fa885](https://github.com/beat-forge/clients/commit/e7fa885a0be22e229bfa3a06a49125a73faa0cd8))
* **web:** landing v2 navbar ([ad697db](https://github.com/beat-forge/clients/commit/ad697dbd0b7dc233a07d4c9ad80dd943b43936fd))
* **web:** login href ([22800bc](https://github.com/beat-forge/clients/commit/22800bcad797c4cbdb52e8208ac34c45d044ed56))
* **web:** migrate landing page ([cb148c5](https://github.com/beat-forge/clients/commit/cb148c5dbeedd2f26c9ccb893546d2cf28aecb3e))
* **web:** opengraph meta tags ([fde34cc](https://github.com/beat-forge/clients/commit/fde34cc56bbc96f22c5a60a765e66cb21f64149c))
* **web:** optimize animations ([ae7e7b6](https://github.com/beat-forge/clients/commit/ae7e7b65ffa03b5b3b5a4971824d2936002125f3))
* **web:** sveltekit demo with tailwind ([2a362d2](https://github.com/beat-forge/clients/commit/2a362d2008a71c8ffd47f7a674918e4f18d68540))
* **web:** trigger build ([6951a38](https://github.com/beat-forge/clients/commit/6951a38f775d66cdbaf15105962c3ce7247d6bfe))

### Bug Fixes

* added total mods to user page, and made mobile button smaller on mod page ([bcd8905](https://github.com/beat-forge/clients/commit/bcd89050e46a248a0ba5662b1afca75111f0b279))
* auth now working ([0034cf0](https://github.com/beat-forge/clients/commit/0034cf0aa9d63853f8c3a0f3b0fa8ba5228bfb2d))
* clean up dockerfile ([a97565c](https://github.com/beat-forge/clients/commit/a97565ca7eae7d57c7d9f1ff8129277a07945e89))
* fixed env example and fixed error page to be properly centered ([5c07943](https://github.com/beat-forge/clients/commit/5c0794344b5373710b6df13c2959004f1209aaaf))
* fixed time inconsistencies on discover and profile page ([bbcadc3](https://github.com/beat-forge/clients/commit/bbcadc3420a2c1d97a79a0d41e9a327da118dcdb))
* fonts project-wide ([5494385](https://github.com/beat-forge/clients/commit/549438552f1cb1bbe929104a6e689983fc848133))
* format ([f48e69f](https://github.com/beat-forge/clients/commit/f48e69fc592155eb3e2f1301cd4e40ee4e40f2a8))
* OKAY ACTUALLY FIXED DATES ([27b91f6](https://github.com/beat-forge/clients/commit/27b91f6cdb707a7c45b58d5da0d18707bcd720a7))
* put docker:build in correct package.json ([1813363](https://github.com/beat-forge/clients/commit/1813363d077d4e83d701a9afb52437e7fa3ccb43))
* remove compile time env check ([fbf3859](https://github.com/beat-forge/clients/commit/fbf3859df2eea2c1fdfedc3d67fa9e3825f67c52))
* **web:** actually fix doublescroll ([281900f](https://github.com/beat-forge/clients/commit/281900f5f9ad527071c782e35a0bea01f5eed081))
* **web:** add responsive sizes to headline text ([6bd3ce3](https://github.com/beat-forge/clients/commit/6bd3ce3ad5a963d1802710176dc756ef7ba09f83))
* **web:** catch if mod list is empty ([8fe88f4](https://github.com/beat-forge/clients/commit/8fe88f4ae4d9b58123c7d161cb0c31c3e7d3e2d3))
* **web:** catch jwt error on login ([46fd531](https://github.com/beat-forge/clients/commit/46fd531222b786e035a41fa32792b13acb50e08f))
* **web:** center mobile hamburger on landingv2 ([e78b625](https://github.com/beat-forge/clients/commit/e78b625abc3b7177b9c9fed1ad405dc6b621fb71))
* **web:** center navbar links to page ([058b541](https://github.com/beat-forge/clients/commit/058b5410884efea9db8cd6fe8a364b3980895336))
* **web:** correct fonts againn ([db5d8c8](https://github.com/beat-forge/clients/commit/db5d8c81f82a6633aece185fef89ba78de85e892))
* **web:** disclaimer clipping with landingvideo ([713c4d6](https://github.com/beat-forge/clients/commit/713c4d661f4ea5760acaba495a04daba2b744ac4))
* **web:** ensure components are imported via $ ([5addb3d](https://github.com/beat-forge/clients/commit/5addb3dafbe0da8957188e6004ecabef6649a360))
* **web:** fixed items not showing correct date ([7922629](https://github.com/beat-forge/clients/commit/792262933041c3fdf25a43b7246b6bef86687466))
* **web:** make landingvideo unselectable ([cf6aab0](https://github.com/beat-forge/clients/commit/cf6aab0c051008fcdb49c472660844256efea031))
* **web:** no more cookies, only localstorage. ([4cf6ebe](https://github.com/beat-forge/clients/commit/4cf6ebe1880e614dd5be841795a5905bba38f6c2))
* **web:** nonexistent route ([95e95fc](https://github.com/beat-forge/clients/commit/95e95fc88f36ef26acbd358b8fc6ec3dd6c8f43b))
* **web:** possible fix for doublescrolling ([ed6f045](https://github.com/beat-forge/clients/commit/ed6f04542e8c07d4d8abd3680ed5f9010f3e2af9))
* **web:** ui package in content[] ([3420dd3](https://github.com/beat-forge/clients/commit/3420dd3a8c4b7c2b2382673c706bc658c812065e))
* **web:** use sveltekit fetch rather than window.fetch ([05b694d](https://github.com/beat-forge/clients/commit/05b694df0e33e92b46d4dd795afe95a4f3e72320))
* went back to proper ([8c9de01](https://github.com/beat-forge/clients/commit/8c9de0160d9b090e338c14b74d6e0b7fe0344464))
* working .env ([b3e8301](https://github.com/beat-forge/clients/commit/b3e830142ca98abddd209afcbffdd624f853d134))

### Performance Improvements

* optimize images on buildtime (lossless) ([61980e7](https://github.com/beat-forge/clients/commit/61980e71eff1a0a9417db9e2bf39252010348324))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by ferothefox** [comment]
LGTM

**Comment by ferothefox** [comment]
DOES NOT LGTM

**Comment by ChecksumDev** [comment]
image
"LGTM"

**Comment by sargon64** [comment]
CAN CONFIRM DOES NOT LGTM

**Comment by ChecksumDev** [comment]
lgtm

**Comment by ferothefox** [comment]
lgtm

**Comment by Wamy-Dev** [comment]
lgtm yus

**Comment by sargon64** [comment]
lgtm

**Review by ferothefox — APPROVED** [review]
lgtm

**Comment by ChecksumDev** [comment]
:robot: Release is at https://github.com/beat-forge/clients/releases/tag/web-v1.0.0 :sunflower:

**Pull request merged**
